/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as rootRouteRouteImport } from './routes/(root)/route'
import { Route as rootIndexRouteImport } from './routes/(root)/index'
import { Route as rootCheckoutRouteImport } from './routes/(root)/checkout'
import { Route as rootCategoriesRouteImport } from './routes/(root)/categories'
import { Route as rootCartRouteImport } from './routes/(root)/cart'
import { Route as rootProductsIndexRouteImport } from './routes/(root)/products/index'
import { Route as rootProductsProductIdRouteImport } from './routes/(root)/products/$productId'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const rootRouteRoute = rootRouteRouteImport.update({
  id: '/(root)',
  getParentRoute: () => rootRouteImport,
} as any)
const rootIndexRoute = rootIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteRoute,
} as any)
const rootCheckoutRoute = rootCheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteRoute,
} as any)
const rootCategoriesRoute = rootCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => rootRouteRoute,
} as any)
const rootCartRoute = rootCartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteRoute,
} as any)
const rootProductsIndexRoute = rootProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => rootRouteRoute,
} as any)
const rootProductsProductIdRoute = rootProductsProductIdRouteImport.update({
  id: '/products/$productId',
  path: '/products/$productId',
  getParentRoute: () => rootRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/cart': typeof rootCartRoute
  '/categories': typeof rootCategoriesRoute
  '/checkout': typeof rootCheckoutRoute
  '/': typeof rootIndexRoute
  '/products/$productId': typeof rootProductsProductIdRoute
  '/products': typeof rootProductsIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/cart': typeof rootCartRoute
  '/categories': typeof rootCategoriesRoute
  '/checkout': typeof rootCheckoutRoute
  '/': typeof rootIndexRoute
  '/products/$productId': typeof rootProductsProductIdRoute
  '/products': typeof rootProductsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(root)': typeof rootRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/(root)/cart': typeof rootCartRoute
  '/(root)/categories': typeof rootCategoriesRoute
  '/(root)/checkout': typeof rootCheckoutRoute
  '/(root)/': typeof rootIndexRoute
  '/(root)/products/$productId': typeof rootProductsProductIdRoute
  '/(root)/products/': typeof rootProductsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/login'
    | '/register'
    | '/cart'
    | '/categories'
    | '/checkout'
    | '/'
    | '/products/$productId'
    | '/products'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/register'
    | '/cart'
    | '/categories'
    | '/checkout'
    | '/'
    | '/products/$productId'
    | '/products'
  id:
    | '__root__'
    | '/(root)'
    | '/login'
    | '/register'
    | '/(root)/cart'
    | '/(root)/categories'
    | '/(root)/checkout'
    | '/(root)/'
    | '/(root)/products/$productId'
    | '/(root)/products/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  rootRouteRoute: typeof rootRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(root)': {
      id: '/(root)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof rootRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(root)/': {
      id: '/(root)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof rootIndexRouteImport
      parentRoute: typeof rootRouteRoute
    }
    '/(root)/checkout': {
      id: '/(root)/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof rootCheckoutRouteImport
      parentRoute: typeof rootRouteRoute
    }
    '/(root)/categories': {
      id: '/(root)/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof rootCategoriesRouteImport
      parentRoute: typeof rootRouteRoute
    }
    '/(root)/cart': {
      id: '/(root)/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof rootCartRouteImport
      parentRoute: typeof rootRouteRoute
    }
    '/(root)/products/': {
      id: '/(root)/products/'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof rootProductsIndexRouteImport
      parentRoute: typeof rootRouteRoute
    }
    '/(root)/products/$productId': {
      id: '/(root)/products/$productId'
      path: '/products/$productId'
      fullPath: '/products/$productId'
      preLoaderRoute: typeof rootProductsProductIdRouteImport
      parentRoute: typeof rootRouteRoute
    }
  }
}

interface rootRouteRouteChildren {
  rootCartRoute: typeof rootCartRoute
  rootCategoriesRoute: typeof rootCategoriesRoute
  rootCheckoutRoute: typeof rootCheckoutRoute
  rootIndexRoute: typeof rootIndexRoute
  rootProductsProductIdRoute: typeof rootProductsProductIdRoute
  rootProductsIndexRoute: typeof rootProductsIndexRoute
}

const rootRouteRouteChildren: rootRouteRouteChildren = {
  rootCartRoute: rootCartRoute,
  rootCategoriesRoute: rootCategoriesRoute,
  rootCheckoutRoute: rootCheckoutRoute,
  rootIndexRoute: rootIndexRoute,
  rootProductsProductIdRoute: rootProductsProductIdRoute,
  rootProductsIndexRoute: rootProductsIndexRoute,
}

const rootRouteRouteWithChildren = rootRouteRoute._addFileChildren(
  rootRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  rootRouteRoute: rootRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
